export const ROUTE_API = "/api";
export const ROUTE_AUTH = "/auth";
export const ROUTE_USER_INFO = "/user/info";
export const ROUTE_USER_INFO_BY_ID = "/user/info/id/:id";
export const ROUTE_USER_INFO_BY_EMAIL = "/user/info/email/:email";
export const ROUTE_REG = "/registration";
export const ROUTE_CHECK= "/check";
export const ROUTE_USER_EMAIL = "/user/email";
export const ROUTE_USER_LOGIN = "/user/login";
